export const States=[
	'GeoDef 01',
	'GeoDef 02',
	'GeoDef 03',
	'GeoDef 04',
	'GeoDef 05',
	'GeoDef 06',
	'GeoDef 07',
	'GeoDef 08',
	'GeoDef 09',
	'GeoDef 10',
	'GeoDef 11',
	'GeoDef 12',
	'GeoDef 13',
	'Alabama',
	'Alaska',
	'Arizona',
	'Arkansas',
	'California',
	'Colorado',
	'Connecticut',
	'Delaware',
	'Florida',
	'Georgia',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine',
	'Maryland',
	'Massachusetts',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'New Hampshire',
	'New Jersey',
	'New Mexico',
	'New York',
	'North Carolina',
	'North Dakota',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'Rhode Island',
	'South Carolina',
	'South Dakota',
	'Tennessee',
	'Texas',
	'Utah',
	'Vermont',
	'Virginia',
	'Washington',
	'West Virginia',
	'Wisconsin',
	'Wyoming'
]
export const Categories=[
	'Category 01',
	'Category 02',
	'Category 03',
	'Category 04',
	'Category 05',
	'Category 06',
	'Category 07',
	'Category 08',
	'Category 09',
	'Category 10',
	'Agriculture/Food',
	'Animals',
	'Armed Forces/National Security',
	'Arts, Culture, Religion',
	'Civil Rights/Liberties,Minority Issues',
	'Commerce',
	'Congress',
	'Crime/Law Enforcement',
	'Economics/Public Finance',
	'Education',
	'Emergency Management',
	'Energy',
	'Environment Protection',
	'Families',
	'Finance/Financial Sector',
	'Foreign Trade/International Finance',
	'Government Operations/Politics',
	'Health',
	'Housing/Community Development',
	'Immigration',
	'International Affairs',
	'Labor/Employment',
	'Law',
	'Native Americans',
	'Public Lands/Natural Resources',
	'Science, Technology, Communication',
	'Social Sciences/History',
	'Social Welfare',
	'Sports/Recreation',
	'Taxation',
	'Transportation/Public Works',
	'Water Resources Development'
]