on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
name: Build Server
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    defaults:
      run:
        working-directory: server
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm install
      - run: npm run lint
      - run: npm run test
