name: Mark stale issues and pull requests
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-taken: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: ':wave: Hi! This issue has been marked stale due to inactivity. If no further activity occurs within the next 7 days, it will automatically be closed.'
        stale-pr-message: ':wave: Hi! This pull request has been marked stale due to inactivity. If no further activity occurs within the next 7 days, it will automatically be closed.'
        stale-issue-label: 'stale'
        exempt-issue-label: 'keep-open'
        remove-stale-when-updated: true
        stale-issue-label: 'Stale'
        stale-pr-label: 'Stale'
        labels-to-add-when-unstale: 'help-wanted'
        days-before-stale: 60
        days-before-close: 7
